# Generated by Django 4.1.4 on 2023-02-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentsessionalrecord_additional_doc_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentnextofkininfo',
            name='address',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
    ]
