# Generated by Django 4.1.4 on 2023-02-04 17:19

from django.db import migrations, models
import students.models
import students.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_studentnextofkininfo_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentacademicdetails',
            options={'ordering': ['-student'], 'verbose_name': 'Student Academic Details', 'verbose_name_plural': 'Students Academic Details'},
        ),
        migrations.AlterModelOptions(
            name='studentcontactinfo',
            options={'ordering': ['-student'], 'verbose_name': 'Student Contact Record', 'verbose_name_plural': 'Student Contact Records'},
        ),
        migrations.AlterModelOptions(
            name='studentgeneraldocs',
            options={'ordering': ['-student'], 'verbose_name': 'Student General Docs', 'verbose_name_plural': 'Students General Docs'},
        ),
        migrations.AlterModelOptions(
            name='studenthealthinfo',
            options={'ordering': ['-student'], 'verbose_name': 'Students Health Record', 'verbose_name_plural': 'Students Health Records'},
        ),
        migrations.AlterModelOptions(
            name='studentnextofkininfo',
            options={'ordering': ['-student'], 'verbose_name': "Student's Next of Kin Record", 'verbose_name_plural': "Students' Next of Kin Records"},
        ),
        migrations.AlterModelOptions(
            name='studentplaceoforigininfo',
            options={'ordering': ['-student'], 'verbose_name': 'Student Place of Origin Info', 'verbose_name_plural': 'Student Origins Info'},
        ),
        migrations.AlterModelOptions(
            name='studentsessionalrecord',
            options={'ordering': ['-student'], 'verbose_name_plural': 'Student Sessional Records'},
        ),
        migrations.AlterField(
            model_name='studentsessionalrecord',
            name='additional_doc_1',
            field=models.ImageField(blank=True, null=True, upload_to=students.models.RecordUploadTo(''), validators=[students.validators.validate_file_size], verbose_name='Additional Document 1'),
        ),
        migrations.AlterField(
            model_name='studentsessionalrecord',
            name='additional_doc_2',
            field=models.ImageField(blank=True, null=True, upload_to=students.models.RecordUploadTo(''), validators=[students.validators.validate_file_size], verbose_name='Additional Document 2'),
        ),
    ]
