# Generated by Django 4.1.4 on 2023-02-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_studentacademicdetails_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentacademicdetails',
            name='jamb_number',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
