# Generated by Django 4.1.4 on 2023-02-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_studentacademicdetails_jamb_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentacademicdetails',
            name='jamb_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
