# Generated by Django 4.1.4 on 2023-02-05 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('students', '0007_alter_studentacademicdetails_jamb_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentacademicdetails',
            options={'ordering': ['-created_at'], 'verbose_name': 'Student Academic Details', 'verbose_name_plural': 'Students Academic Details'},
        ),
        migrations.AlterModelOptions(
            name='studentbulkupload',
            options={'ordering': ['csv_file']},
        ),
        migrations.AlterModelOptions(
            name='studentcontactinfo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Student Contact Record', 'verbose_name_plural': 'Student Contact Records'},
        ),
        migrations.AlterModelOptions(
            name='studentgeneraldocs',
            options={'ordering': ['-created_at'], 'verbose_name': 'Student General Docs', 'verbose_name_plural': 'Students General Docs'},
        ),
        migrations.AlterModelOptions(
            name='studenthealthinfo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Students Health Record', 'verbose_name_plural': 'Students Health Records'},
        ),
        migrations.AlterModelOptions(
            name='studentnextofkininfo',
            options={'ordering': ['-created_at'], 'verbose_name': "Student's Next of Kin Record", 'verbose_name_plural': "Students' Next of Kin Records"},
        ),
        migrations.AlterModelOptions(
            name='studentplaceoforigininfo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Student Place of Origin Info', 'verbose_name_plural': 'Student Origins Info'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Student Profile', 'verbose_name_plural': 'Students Profiles'},
        ),
        migrations.AlterModelOptions(
            name='studentsessionalrecord',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Student Sessional Records'},
        ),
        migrations.AlterField(
            model_name='studentbulkupload',
            name='csv_file',
            field=models.FileField(upload_to='students/bulkupload/', verbose_name='Student CSV'),
        ),
        migrations.AlterField(
            model_name='studenthealthinfo',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=30),
        ),
        migrations.AlterField(
            model_name='studentsessionalrecord',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.academicsession'),
        ),
    ]
