# Generated by Django 4.1.4 on 2023-02-14 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('students', '0009_alter_studentbulkupload_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsessionalrecord',
            name='academic_session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='administration.academicsession'),
            preserve_default=False,
        ),
    ]
