# Generated by Django 4.1.4 on 2023-02-14 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_academicsession_is_update_level_cord'),
        ('students', '0010_alter_studentsessionalrecord_academic_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsessionalrecord',
            name='academic_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='administration.academicsession'),
        ),
    ]
