# Generated by Django 4.1.4 on 2023-02-20 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_studentsessionalrecord_academic_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='pin_code',
        ),
    ]
