# Generated by Django 4.1.4 on 2023-02-20 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_smsmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SMSMessage',
            new_name='StudentSMSMessaging',
        ),
    ]
