# Generated by Django 4.1.4 on 2023-02-26 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_alter_togglesession_options'),
        ('students', '0014_rename_smsmessage_studentsmsmessaging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsessionalrecord',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.academicsession'),
        ),
    ]
