# Generated by Django 4.1.4 on 2023-02-27 08:40

from django.db import migrations, models
import students.models
import students.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_alter_studentsessionalrecord_academic_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgeneraldocs',
            name='a_level',
            field=models.ImageField(blank=True, null=True, upload_to=students.models.StudentUploadTo(''), validators=[students.validators.validate_file_size], verbose_name='A Level Result (For D.E. Students)'),
        ),
    ]
