# Generated by Django 4.1.7 on 2023-05-17 08:59

from django.db import migrations, models
import students.models
import students.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_studentgeneraldocs_a_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgeneraldocs',
            name='a_level',
            field=models.ImageField(blank=True, default='Image-Gallery-SVG.png', null=True, upload_to=students.models.StudentUploadTo(''), validators=[students.validators.validate_file_size], verbose_name='A Level Result (For D.E. Students)'),
        ),
        migrations.AlterField(
            model_name='studentgeneraldocs',
            name='birth_cert',
            field=models.ImageField(blank=True, default='Image-Gallery-SVG.png', null=True, upload_to=students.models.StudentUploadTo(''), validators=[students.validators.validate_file_size], verbose_name='Birth Certificate'),
        ),
        migrations.AlterField(
            model_name='studentgeneraldocs',
            name='jamb_adm_cert',
            field=models.ImageField(blank=True, default='Image-Gallery-SVG.png', null=True, upload_to=students.models.StudentUploadTo(''), validators=[students.validators.validate_file_size], verbose_name='JAMB Admission Letter'),
        ),
        migrations.AlterField(
            model_name='studentgeneraldocs',
            name='lg_cert',
            field=models.ImageField(blank=True, default='Image-Gallery-SVG.png', null=True, upload_to=students.models.StudentUploadTo(''), validators=[students.validators.validate_file_size], verbose_name='Local Govt Certificate'),
        ),
        migrations.AlterField(
            model_name='studentgeneraldocs',
            name='medical_fitness',
            field=models.ImageField(blank=True, default='Image-Gallery-SVG.png', null=True, upload_to=students.models.StudentUploadTo(''), validators=[students.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='studentgeneraldocs',
            name='o_level',
            field=models.ImageField(blank=True, default='Image-Gallery-SVG.png', null=True, upload_to=students.models.StudentUploadTo(''), validators=[students.validators.validate_file_size], verbose_name="O' Level Result"),
        ),
        migrations.AlterField(
            model_name='studentgeneraldocs',
            name='pri_cert',
            field=models.ImageField(blank=True, default='Image-Gallery-SVG.png', null=True, upload_to=students.models.StudentUploadTo(''), validators=[students.validators.validate_file_size], verbose_name='Primary Certificate'),
        ),
        migrations.AlterField(
            model_name='studentgeneraldocs',
            name='sch_testimonial',
            field=models.ImageField(blank=True, default='Image-Gallery-SVG.png', null=True, upload_to=students.models.StudentUploadTo(''), validators=[students.validators.validate_file_size], verbose_name='School Leaving Certificate'),
        ),
        migrations.AlterField(
            model_name='studentgeneraldocs',
            name='school_adm_letter',
            field=models.ImageField(blank=True, default='Image-Gallery-SVG.png', null=True, upload_to=students.models.StudentUploadTo(''), validators=[students.validators.validate_file_size], verbose_name='School Admission Letter'),
        ),
    ]
