# Generated by Django 4.1.7 on 2023-05-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_remove_studentprofile_has_graduated'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsmsmessaging',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.RemoveField(
            model_name='studentsmsmessaging',
            name='student',
        ),
        migrations.AddField(
            model_name='studentsmsmessaging',
            name='student',
            field=models.ManyToManyField(to='students.student'),
        ),
    ]
