# Generated by Django 4.1.7 on 2023-05-17 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_studentsmsmessaging_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsmsmessaging',
            old_name='date',
            new_name='date_created',
        ),
    ]
