# Generated by Django 4.1.7 on 2023-05-17 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_rename_date_studentsmsmessaging_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsmsmessaging',
            name='student',
        ),
        migrations.AddField(
            model_name='studentsmsmessaging',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
