# Generated by Django 4.1.4 on 2023-02-02 06:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=150, verbose_name='Department Name')),
                ('dept_code', models.CharField(max_length=50, verbose_name='Department Code')),
                ('establish_date', models.DateField(default=datetime.datetime.now, verbose_name='Establishment Date')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=150)),
                ('faculty_code', models.CharField(max_length=50)),
                ('establish_date', models.DateField(default=datetime.datetime.now, verbose_name='Establishment Date')),
            ],
            options={
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prog_name', models.CharField(max_length=150, verbose_name='Programme Name')),
                ('prog_duration', models.IntegerField(verbose_name='Programme Duration')),
                ('establish_date', models.DateField(default=datetime.datetime.now, verbose_name='Establishment Date')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='faculty.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='faculty.faculty')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='faculty.faculty'),
        ),
    ]
