# Generated by Django 4.1.4 on 2023-02-05 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['dept_code']},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['faculty_code'], 'verbose_name_plural': 'Faculties'},
        ),
        migrations.AlterModelOptions(
            name='programme',
            options={'ordering': ['prog_name']},
        ),
    ]
