# Generated by Django 4.1.4 on 2023-02-26 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_alter_department_options_alter_faculty_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='establish_date',
            new_name='established_date',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='establish_date',
            new_name='established_date',
        ),
        migrations.RenameField(
            model_name='programme',
            old_name='establish_date',
            new_name='established_date',
        ),
    ]
