import Head from 'next/head';
import Image from 'next/image';

export default function Login() {
  return (
    <>
      <Head>
        <title>Login</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="container d-flex flex-column justify-content-center min-vh-100">
          <div className="row justify-content-center">
            <div className="col-lg-5">
              <div className="border rounded-4 py-5 px-3 position-relative">
                <div className="d-flex flex-column align-items-center">
                  <Image src={'/images/logo.jpg'} height="80" width="80" />
                  <h4>Paperless FCSIT</h4>
                </div>

                <form action="" className="w-100">
                  <div className="row">
                    <div className="col-12">
                      <div className="form-group">
                        <label htmlFor="" className="form-label fw-bold">
                          Email:
                        </label>
                        <input
                          type="email"
                          className="form-control py-2"
                          placeholder="Please enter your email address"
                        />
                      </div>{' '}
                    </div>
                    <div className="col-12">
                      <div className="form-group">
                        <label htmlFor="" className="fw-bold">
                          Password:
                        </label>
                        <input
                          type="password"
                          className="form-control"
                          placeholder="Enter your secured password"
                        />
                      </div>
                    </div>
                    <div className="col-12 mt-4 d-flex justify-content-end">
                      <input
                        type="submit"
                        className="btn btn-primary px-5"
                        value="Login"
                      />
                    </div>

                    <div className="d-flex justify-content-center mt-3 position-absolute bottom-0">
                      <p className="form-text">
                        &copy; Project build by Ahmad Sheikh & Ahmad
                        Sherrifudeen
                      </p>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
