# Generated by Django 4.1.4 on 2023-02-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=200, null=True, unique=True)),
                ('is_current_session', models.BooleanField(blank=True, default=False, null=True)),
                ('update_student_levels', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
