# Generated by Django 4.1.4 on 2023-02-14 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicsession',
            old_name='update_student_levels',
            new_name='is_update_student_levels',
        ),
    ]
