# Generated by Django 4.1.4 on 2023-02-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_rename_update_student_levels_academicsession_is_update_student_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='is_update_level_cord',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
