# Generated by Django 4.1.4 on 2023-02-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_alter_academicsession_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
