# Generated by Django 4.1.4 on 2023-02-19 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_alter_academicsession_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicsession',
            name='is_current_session',
        ),
        migrations.CreateModel(
            name='ToggleSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current_session', models.BooleanField(blank=True, default=False, null=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administration.academicsession')),
            ],
        ),
    ]
