# Generated by Django 4.1.4 on 2023-02-19 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_remove_academicsession_is_current_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='togglesession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='togglesession',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
