# Generated by Django 4.1.4 on 2023-02-20 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_academicsession_modified_at_togglesession_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='togglesession',
            options={'verbose_name': 'Toggle Session On/Off', 'verbose_name_plural': 'Toggle Sessions On/Off'},
        ),
    ]
