# Generated by Django 4.1.4 on 2023-02-26 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_alter_togglesession_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='togglesession',
            options={'ordering': ['-session'], 'verbose_name': 'Toggle Session On/Off', 'verbose_name_plural': 'Toggle Sessions On/Off'},
        ),
    ]
