# Generated by Django 4.1.4 on 2023-02-02 06:08

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import students.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelCoordinator',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.user',),
            managers=[
                ('level_cords', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LevelCoordinatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='staff/passports', validators=[students.validators.validate_file_size])),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Male')], default='MALE', max_length=10)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_cords', to='faculty.department')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_cords', to='faculty.faculty')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='level_cord', to='level_coordinating.levelcoordinator')),
            ],
            options={
                'verbose_name': 'Lecturer Coordinator Profile',
                'verbose_name_plural': 'Level Cord Profiles',
            },
        ),
        migrations.CreateModel(
            name='CoordinatingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_level', models.PositiveSmallIntegerField(choices=[(100, '100 Level'), (200, '200 Level'), (300, '300 Level'), (400, '400 Level'), (500, 'Spill Over 1'), (600, 'Spill Over 2'), (700, 'Spill Over 3')], default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_cords', to='faculty.programme')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_cords', to='level_coordinating.levelcoordinator')),
            ],
            options={
                'verbose_name': 'Lecturer Coordinating Info',
                'verbose_name_plural': 'Lecturers Coordinating Info',
                'unique_together': {('programme', 'assigned_level')},
            },
        ),
    ]
