# Generated by Django 4.1.4 on 2023-02-02 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
        ('level_coordinating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelcoordinatorprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_cords', to='faculty.department'),
        ),
        migrations.AlterField(
            model_name='levelcoordinatorprofile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=10),
        ),
    ]
