# Generated by Django 4.1.4 on 2023-02-02 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
        ('level_coordinating', '0002_alter_levelcoordinatorprofile_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinatinginfo',
            name='programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_cords', to='faculty.programme'),
        ),
    ]
