# Generated by Django 4.1.4 on 2023-02-16 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('level_coordinating', '0003_alter_coordinatinginfo_programme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinatinginfo',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_cords', to='level_coordinating.levelcoordinator'),
        ),
    ]
