# Generated by Django 4.1.4 on 2023-02-18 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level_coordinating', '0004_alter_coordinatinginfo_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinatinginfo',
            options={'ordering': ['assigned_level', 'programme'], 'verbose_name': 'Lecturer Coordinating Info', 'verbose_name_plural': 'Lecturers Coordinating Info'},
        ),
    ]
