# Generated by Django 4.1.4 on 2023-02-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level_coordinating', '0005_alter_coordinatinginfo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Student SMS Message',
                'verbose_name_plural': 'Student SMS Messages',
            },
        ),
    ]
