# Generated by Django 4.1.4 on 2023-02-20 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level_coordinating', '0007_rename_title_smsmessage_student_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smsmessage',
            old_name='student_name',
            new_name='student_reg_number',
        ),
    ]
