# Generated by Django 4.1.4 on 2023-02-20 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level_coordinating', '0008_rename_student_name_smsmessage_student_reg_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMSMessage',
        ),
    ]
