# Generated by Django 4.1.4 on 2023-02-04 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Entered phone number isn't in a right format!", regex='^[0-9]{10,15}$')]),
        ),
    ]
